### ISSUE TITLE
Leech Issue

### ISSUE THREAD

**Issue by RealNoobieDrive** [arshsisodiya/helios-mirror#77]
Don't know why but sometimes leech is causing r14 memory exceed issue, most of the cases they just work for 3-4 days ,although the bots that were used only for mirror working fine even after 10-15 days..

Sometimes just 1 task is causing r14 memory exceed..

Ban is happening at the time of splitting.

Don't know if it can be solved or not ,just letting you know

**Comment by arshsisodiya** [comment]
try restarting your dyno, don't leech too many files at the same time, don't leech too many files more than 2 GB,

**Comment by LeoBonharts** [comment]
Could say several days ago i doesn't have any issue with leeching big files even 30Gb files and splitting files and upload to tg, now even with telegram premium account with changes for upload to telegram the bot will suspend i think the problem is that heroku know the splitting or heavy processing should change the splitting code and upload code to fix the issue.
